# Header
menu:
  主页: /
  所有文章: /archives
  关于我: /about

# SubNav
subnav:
  github: "https://github.com/xchunzhao"
  weibo: "http://weibo.com/u/3748901250"
  rss: /atom.xml
  # rss: "#"
  # zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
rss: /atom.xml


# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://avatars0.githubusercontent.com/u/13491131?v=3&s=460"
#是否开启分享
share: true
share_jia: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends: false

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: sssss
